### ISSUE TITLE
Projected labels are missing

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/vertebral-labeling-validation#1]
Tested: 76dcf0dee49deaca419feb5d7b5b9987bb575b59
SCT: 2cf7545ba5f9f8756743b09fc68fe2b614c07111
Data: 47a3bdcddeef8da0e5f19d15e9b1464bccf67b12

Example below, label=3 is missing from the projected GT:

```bash
sct_label_utils -i /Users/julien/code/vertebral-labeling-validation/results_20201022/results/data/derivatives/labels/sub-amu02/anat/sub-amu02_T1w_projected-gt.nii.gz -display

--
Spinal Cord Toolbox (git-master-2cf7545ba5f9f8756743b09fc68fe2b614c07111)

Position=(95,113,105) -- Value= 4.0
Position=(94,114,91) -- Value= 5.0
Position=(94,113,78) -- Value= 6.0
Position=(94,109,66) -- Value= 7.0
Position=(94,101,53) -- Value= 8.0
Position=(95,89,36) -- Value= 9.0
Position=(97,75,15) -- Value= 10.0

sct_label_utils -i /Users/julien/code/vertebral-labeling-validation/results_20201022/results/data/derivatives/labels/sub-amu02/anat/sub-amu02_T1w_labels-disc-manual.nii.gz -display

--
Spinal Cord Toolbox (git-master-2cf7545ba5f9f8756743b09fc68fe2b614c07111)

Position=(96,120,123) -- Value= 3
Position=(96,124,107) -- Value= 4
Position=(96,125,91) -- Value= 5
Position=(96,124,75) -- Value= 6
Position=(96,118,60) -- Value= 7
Position=(96,107,47) -- Value= 8
Position=(96,95,31) -- Value= 9
Position=(96,79,13) -- Value= 10
```

**Comment by lrouhier** [comment]
I'll open an issue in SCT because this is an `sct_label_vertebrae` issue. My best guess is that the straightening [here](https://github.com/neuropoly/spinalcordtoolbox/blob/d9a8a88fb2e0a6462a46db572ed1e222fe1a4681/scripts/sct_label_vertebrae.py#L340) causes the issue. I will check that out and come back to you.

**Comment by lrouhier** [comment]
Update: It is not the straightening but it appears to come from [label disc](https://github.com/neuropoly/spinalcordtoolbox/blob/d9a8a88fb2e0a6462a46db572ed1e222fe1a4681/spinalcordtoolbox/vertebrae/core.py#L518)

So what is happening is that `sct_label_vertebrae` is using this segmentation to create the points for the disc:
![image](https://user-images.githubusercontent.com/22171999/97021015-4c68b780-1520-11eb-876e-44599ae31c94.png)

The script is then retrieving the transition unfortunately the first disc will always be missing as it represents the top of the segmentation. 
A disc at the top is not always needed (like the disc 0 does not need to exist) I opened an issue to discuss that [here](https://github.com/neuropoly/spinalcordtoolbox/issues/2967)

**Comment by joshuacwnewton** [comment]
spinalcordtoolbox/spinalcordtoolbox#2967 was merged, closing for clean-up purposes.
