### ISSUE TITLE
Processed data should be placed under sub-folder $PATH_DATA_PROCESSED

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/vertebral-labeling-validation#3]
As of 76dcf0dee49deaca419feb5d7b5b9987bb575b59, processed data are copied and processed under `$PATH_RESULTS`. To follow the convention introduced by [spine-generic](https://github.com/spine-generic/spine-generic/blob/v2.5/process_data.sh), processed data should go under `$PATH_DATA_PROCESSED`, while results (e.g. CSV file) go under `$PATH_RESULTS`

**Comment by lrouhier** [comment]
done in dfde1adb12091d07ce4560c8c1d46a859ac5f4d4
