### ISSUE TITLE
run_prediction.sh: Loop across contrasts

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/vertebral-labeling-validation#5]
The code is highly duplicated for T1 and T2 processing. It would be trivial to make a loop across the list ("T1", "T2"). Since this is a low-hanging fruit, I suggest to do it.

The same applies to other scripts.

**Comment by lrouhier** [comment]
done in bb627766a16f645fddb35a8c555dbd6f698590c8, ff7360ba05c7101be749b1c77182ce2d7d3d620f, 70f27a3a623e1bdc5445c99181dcd096d6cc5444 and 598f7269be53f12dc44f9f2b6de9dadfb5666ff6
